FROM httpd:latest

# Copy website files to the document root (the index.html and other files if there any)
COPY ./html/ /usr/local/apache2/htdocs/

# (Optional) Copy a custom configuration file
# COPY ./confgis/httpd.conf /usr/local/apache2/conf/httpd.conf

